name: My first workflow

on: 
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      
      - name: Executing Shell Script
        run: |
      - name: welcome message
        run: echo "my first github action on job"
        
      - name: welcome message
        run: echo "my first github action on job"

      - name: list files
        run: ls
        
      - name: read file
        run: cat README.md
   
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: adecloudy/ravl
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}