name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4


        - name: Executing Shell Script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
            

        - name: Build and push Docker Image
          uses: mr-smithers-excellent/docker-build-push@v6
          with:
            image: adecloudy/ravl
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
                