name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "my first github action on job"

        - name: list files
          run: ls
        
        - name: read file
          run: cat Readme.md
